# Generated by Django 4.1.2 on 2022-10-14 11:34

import autoslug.fields
import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Category", models.CharField(default="", max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name="WebsiteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("WebsiteName", models.CharField(default="", max_length=50000)),
                (
                    "BlogAuthorImage",
                    models.ImageField(
                        blank=True,
                        max_length=250,
                        null=True,
                        upload_to=blog.models.image_directory_path,
                    ),
                ),
                ("BlogAuthorName", models.CharField(default="", max_length=250)),
                ("BlogAuthorDesc", models.CharField(default="", max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="SinlgeBlogInfo",
            fields=[
                ("BlogMetaDescription", models.CharField(default="", max_length=50000)),
                ("BlogImageURL", models.URLField(default="", max_length=50000)),
                ("BlogH1", models.CharField(default="", max_length=50000)),
                ("BlogH1P", models.TextField(default="", max_length=5000000)),
                ("BlogH2", models.CharField(default="", max_length=50000)),
                ("BlogH2P", models.TextField(default="", max_length=5000000)),
                ("BlogH3", models.CharField(default="", max_length=50000)),
                ("BlogH3P", models.TextField(default="", max_length=5000000)),
                ("BlogH4", models.CharField(default="", max_length=50000)),
                ("BlogH4P", models.TextField(default="", max_length=5000000)),
                ("BlogH5", models.CharField(default="", max_length=50000)),
                ("BlogH5P", models.TextField(default="", max_length=5000000)),
                (
                    "Slug",
                    autoslug.fields.AutoSlugField(
                        default="",
                        editable=False,
                        null=True,
                        populate_from="BlogH1",
                        unique=True,
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.category",
                    ),
                ),
            ],
        ),
    ]
