# Generated by Django 4.1.2 on 2022-10-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="Category",
        ),
        migrations.AddField(
            model_name="category",
            name="Name",
            field=models.CharField(default="", max_length=500),
        ),
    ]
