# Generated by Django 4.1.2 on 2022-10-14 22:05

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_category_category_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="Slug",
            field=autoslug.fields.AutoSlugField(
                default="", editable=False, null=True, populate_from="Name", unique=True
            ),
        ),
    ]
