# Generated by Django 4.1.2 on 2022-10-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_category_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="Slug",
            new_name="CategorySlug",
        ),
    ]
