# Generated by Django 4.1.2 on 2022-10-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_slug_category_categoryslug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="CategorySlug",
        ),
    ]
