# Generated by Django 4.1.2 on 2022-11-06 13:01

import blog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_category_categoryslug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websiteinfo",
            name="BlogAuthorImage",
            field=models.ImageField(
                blank=True,
                max_length=250,
                null=True,
                upload_to=blog.models.image_directory_path,
                validators=[django.core.validators.FileExtensionValidator(["PNG"])],
            ),
        ),
    ]
